ALTER TABLE IF EXISTS public.users
  ADD COLUMN IF NOT EXISTS contacts_total_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS financial_sms_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS financial_credit_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS financial_debit_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS financial_detected_amount NUMERIC(14,2) NOT NULL DEFAULT 0;
