-- Hotfix: enforce broad compatibility for app/runtime queries across core tables.
-- Idempotent by design (IF NOT EXISTS).

-- USERS
ALTER TABLE IF EXISTS public.users
  ADD COLUMN IF NOT EXISTS credit_score INT NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS balance_kes NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS contacts_permission_granted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sms_permission_granted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS contacts_snapshot TEXT,
  ADD COLUMN IF NOT EXISTS sms_snapshot TEXT,
  ADD COLUMN IF NOT EXISTS monthly_income INT,
  ADD COLUMN IF NOT EXISTS salary_range TEXT,
  ADD COLUMN IF NOT EXISTS employer_name TEXT,
  ADD COLUMN IF NOT EXISTS employment_status TEXT,
  ADD COLUMN IF NOT EXISTS date_of_birth TEXT,
  ADD COLUMN IF NOT EXISTS national_id TEXT,
  ADD COLUMN IF NOT EXISTS county TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- LOANS
ALTER TABLE IF EXISTS public.loans
  ADD COLUMN IF NOT EXISTS purpose TEXT,
  ADD COLUMN IF NOT EXISTS loan_type TEXT,
  ADD COLUMN IF NOT EXISTS amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS principal_kes NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS interest_rate NUMERIC(8,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tenure INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS tenure_months INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS total_payable NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS amount_repaid NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS repaid_amount_kes NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS disbursed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS due_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reference_number TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- TRANSACTIONS
ALTER TABLE IF EXISTS public.transactions
  ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT 'Transaction',
  ADD COLUMN IF NOT EXISTS amount_kes NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tx_type TEXT NOT NULL DEFAULT 'DEBIT',
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'APP',
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- PAYMENT INTENTS (compat for webhook/repayment flows)
ALTER TABLE IF EXISTS public.payment_intents
  ADD COLUMN IF NOT EXISTS user_id UUID,
  ADD COLUMN IF NOT EXISTS loan_id UUID,
  ADD COLUMN IF NOT EXISTS amount_kes NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS provider_ref TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
